workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: always

stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
#  - incremental rollout 10%
#  - incremental rollout 25%
#  - incremental rollout 50%
#  - incremental rollout 100%
#  - performance
  - cleanup

variables:
  ROLLOUT_RESOURCE_TYPE: deployment
  POSTGRES_ENABLED: "false"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  STAGING_ENABLED: "true"
  APP_ROOT: /app
  HELM_UPGRADE_EXTRA_ARGS: >
    --set name=$CI_PROJECT_PATH_SLUG
    --set release=$CI_ENVIRONMENT_SLUG
    --set image.repository=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    --set image.tag=$CI_COMMIT_SHA
    
cache:
  paths:
    - ${APP_ROOT}/.m2

include:
  - template: Jobs/Build.gitlab-ci.yml
#  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml